import Product from '../models/Product.js';
import ProductOffer from '../models/ProductOffer.js';

import {
  computeProductMatch,
} from './matchingEngineService.js';

import {
  getBestCustomerOffer,
} from '../utils/offerPresentation.js';

import normalizeCategory from '../utils/normalizeCategory.js';

/**
 * Anonymous recommendation analysis.
 *
 * IMPORTANT:
 * - No Gemini
 * - No Groq
 * - No AI ranking
 * - No AI calls during recommendation generation
 *
 * Product Intelligence may still have been generated by AI upstream.
 * This service only consumes the stored Product Intelligence and performs
 * deterministic user/product matching.
 */

const RECOMMENDATION_CATEGORIES = [
  'Cleansers',
  'Moisturizers',
  'Sunscreens',
  'Serums',
  'Exfoliants',
  'Toners & Essences',
  'Retinoids & Anti-Aging',
  'Eye Creams & Serums',
  'Face Masks',
  'Facial Oils',
];

const getElapsed = (start) =>
  `${Date.now() - start}ms`;

export const runAnonymousAnalysis =
  async ({
    profile,
    consent,
  }) => {
    const requestStart = Date.now();

    console.log(
      '[ANON] Analysis START'
    );

    /*
     * ---------------------------------------------------------
     * 1. LOAD ACTIVE PRODUCTS
     * ---------------------------------------------------------
     */

    let stepStart = Date.now();

    const products =
      await Product.find({
        isActive: true,
      })
        .populate(
          'brand',
          'name'
        )
        .populate(
          'category',
          'name code slug aliases'
        )
        .populate(
          'ingredients',
          'name aliases'
        )
        .populate(
          'keyIngredients',
          'name aliases'
        )
        .lean();

    console.log(
      `[ANON] Products loaded: ${getElapsed(
        stepStart
      )} | count=${products.length}`
    );

    /*
     * ---------------------------------------------------------
     * 2. LOAD ACTIVE OFFERS
     * ---------------------------------------------------------
     */

    stepStart = Date.now();

    const productIds =
      products.map(
        ({ _id }) => _id
      );

    const offers =
      productIds.length
        ? await ProductOffer.find({
            product: {
              $in: productIds,
            },

            isActive: true,
          })
            .populate(
              'retailer',
              'name slug'
            )
            .lean()
        : [];

    console.log(
      `[ANON] Offers loaded: ${getElapsed(
        stepStart
      )} | count=${offers.length}`
    );

    /*
     * ---------------------------------------------------------
     * 3. GROUP OFFERS BY PRODUCT
     * ---------------------------------------------------------
     */

    stepStart = Date.now();

    const offersByProduct =
      offers.reduce(
        (map, offer) => {
          const key =
            offer.product.toString();

          const current =
            map.get(key) || [];

          current.push(offer);

          map.set(
            key,
            current
          );

          return map;
        },
        new Map()
      );

    console.log(
      `[ANON] Offers grouped: ${getElapsed(
        stepStart
      )}`
    );

    /*
     * ---------------------------------------------------------
     * 4. BUILD ALL PRODUCTS
     *
     * Lightweight catalog payload used by the anonymous UI.
     * This is separate from the detailed recommendation result.
     * ---------------------------------------------------------
     */

    stepStart = Date.now();

    const allProducts =
      products.map((product) => {
        const productOffers =
          offersByProduct.get(
            product._id.toString()
          ) || [];

        const customerOffer =
          getBestCustomerOffer(
            productOffers
          );

        return {
          _id: product._id,

          name: product.name,

          brand: product.brand,

          category:
            product.category,

          images:
            product.images || [],

          price:
            customerOffer
              ? Number(
                  customerOffer.price
                )
              : null,

          offerUrl:
            customerOffer?.url ||
            null,
        };
      });

    console.log(
      `[ANON] All products prepared: ${getElapsed(
        stepStart
      )} | count=${allProducts.length}`
    );

    /*
     * ---------------------------------------------------------
     * 5. DETERMINISTIC PRODUCT MATCHING
     *
     * IMPORTANT:
     *
     * This is the only recommendation/scoring step.
     *
     * No Gemini.
     * No Groq.
     * No LLM reranking.
     *
     * computeProductMatch() handles:
     *
     * SkinProfile
     *      ↓
     * Derived requirements
     *      ↓
     * Hard constraints
     *      ↓
     * Product Intelligence
     *      ↓
     * Deterministic compatibility
     * ---------------------------------------------------------
     */

    stepStart = Date.now();

    const scoredProducts =
      products.map((product) => {
        const productOffers =
          offersByProduct.get(
            product._id.toString()
          ) || [];

        const customerOffer =
          getBestCustomerOffer(
            productOffers
          );

        const offerPrice =
          customerOffer
            ? Number(
                customerOffer.price
              )
            : null;

        const matchResult =
          computeProductMatch({
            product,

            skinProfile:
              profile,

            offerPrice,

            currentCategory:
              normalizeCategory(product.category),
          });

        return {
          /*
           * Keep `score` because the anonymous
           * frontend may already consume it.
           *
           * overallScore is the deterministic
           * compatibility score returned by
           * matchingEngineService.
           */
          score:
            Number(
              matchResult.overallScore
            ) || 0,

          overallScore:
            matchResult.overallScore,

          skinCompatibilityScore:
            matchResult.skinCompatibilityScore,

          eligible:
            matchResult.eligible,

          dimensionScores:
            matchResult.dimensionScores,

          positiveReasons:
            matchResult.positiveReasons,

          warnings:
            matchResult.warnings,

          hardConflicts:
            matchResult.hardConflicts,

          confidence:
            matchResult.confidence,

          evidenceConfidence:
            matchResult.evidenceConfidence,

          evidenceLevel:
            matchResult.evidenceLevel,

          withinBudget:
            matchResult.withinBudget,

          budgetConstraint:
            matchResult.budgetConstraint,

          matchedFactors:
            matchResult.matchedFactors ||
            [],

          concernsMatched:
            matchResult.concernsMatched ||
            [],

          concernsNotMatched:
            matchResult.concernsNotMatched ||
            [],

          explanation:
            matchResult.explanation,

          matchingEngineVersion:
            matchResult.matchingEngineVersion,

          /*
           * Keep the complete deterministic result
           * available to the caller.
           */
          matchResult,

          product: {
            _id:
              product._id,

            name:
              product.name,

            brand:
              product.brand,

            category:
              product.category,

            images:
              product.images || [],
          },

          price:
            customerOffer
              ? Number(
                  customerOffer.price
                )
              : null,

          offerUrl:
            customerOffer?.url ||
            null,

          retailer:
            customerOffer?.retailer ||
            null,
        };
      });

    /*
     * ---------------------------------------------------------
     * 6. REMOVE INELIGIBLE PRODUCTS
     *
     * Hard constraints are handled by
     * computeProductMatch().
     *
     * We do NOT ask AI whether a product should
     * be removed.
     * ---------------------------------------------------------
     */

    const eligibleProducts =
      scoredProducts.filter(
        (product) =>
          product.eligible === true
      );

    console.log('[ANON DEBUG] Eligibility breakdown:', JSON.stringify({
      total: scoredProducts.length,
      eligible: eligibleProducts.length,
      ineligible: scoredProducts.length - eligibleProducts.length,
      details: scoredProducts.map(item => ({
        product: item.product?.name,
        eligible: item.eligible,
        hardConflicts: item.hardConflicts,
        concernsNotMatched: item.concernsNotMatched,
        category: item.product?.category,
        normalizedCategory: normalizeCategory(item.product?.category),
      })),
    }, null, 2));

    /*
     * ---------------------------------------------------------
     * 7. CATEGORY-AWARE DETERMINISTIC RANKING
     *
     * IMPORTANT:
     *
     * Recommendations are ranked independently inside each
     * product category.
     *
     * Example:
     *
     * Sunscreens
     *   #1 92
     *   #2 89
     *   #3 84
     *
     * Cleansers
     *   #1 91
     *   #2 87
     *   #3 82
     *
     * A sunscreen can NEVER become "Sunscreen #2"
     * because a cleanser scored higher globally.
     *
     * Ranking priority inside each category:
     *
     * 1. Compatibility score
     * 2. Evidence confidence when compatibility is
     *    within the configured tie window
     * 3. Match confidence
     * 4. Stable product ID
     *
     * Evidence NEVER increases compatibility.
     * ---------------------------------------------------------
     */

    const EVIDENCE_TIE_WINDOW = 2;

    /*
     * Number of recommendations returned PER CATEGORY.
     *
     * This is intentionally independent from the old global
     * candidate limit.
     */
    const RECOMMENDATIONS_PER_CATEGORY = 5;

    const sortCategoryProducts = (products) => {
      return products.sort((a, b) => {
        /*
         * -----------------------------------------------------
         * PRIMARY — COMPATIBILITY
         * -----------------------------------------------------
         */

        const aScore =
          Number(a.score) || 0;

        const bScore =
          Number(b.score) || 0;

        const scoreDifference =
          bScore - aScore;

        /*
         * A materially better compatibility score wins.
         */
        if (
          Math.abs(scoreDifference) >
          EVIDENCE_TIE_WINDOW
        ) {
          return scoreDifference;
        }

        /*
         * -----------------------------------------------------
         * SECONDARY — PRODUCT INTELLIGENCE EVIDENCE
         * -----------------------------------------------------
         *
         * Only used when compatibility scores are close.
         *
         * UNKNOWN evidence remains unknown.
         */
        const aEvidence =
          Number.isFinite(
            Number(a.evidenceConfidence)
          )
            ? Number(a.evidenceConfidence)
            : null;

        const bEvidence =
          Number.isFinite(
            Number(b.evidenceConfidence)
          )
            ? Number(b.evidenceConfidence)
            : null;

        if (
          aEvidence !== null ||
          bEvidence !== null
        ) {
          /*
           * Known evidence beats unknown evidence.
           */
          if (
            aEvidence === null &&
            bEvidence !== null
          ) {
            return 1;
          }

          if (
            aEvidence !== null &&
            bEvidence === null
          ) {
            return -1;
          }

          /*
           * Both known.
           */
          if (
            aEvidence !== null &&
            bEvidence !== null
          ) {
            const evidenceDifference =
              bEvidence - aEvidence;

            if (
              evidenceDifference !== 0
            ) {
              return evidenceDifference;
            }
          }
        }

        /*
         * -----------------------------------------------------
         * TERTIARY — MATCH CONFIDENCE
         * -----------------------------------------------------
         */

        const aConfidence =
          Number(a.confidence);

        const bConfidence =
          Number(b.confidence);

        const safeAConfidence =
          Number.isFinite(aConfidence)
            ? aConfidence
            : -1;

        const safeBConfidence =
          Number.isFinite(bConfidence)
            ? bConfidence
            : -1;

        const confidenceDifference =
          safeBConfidence -
          safeAConfidence;

        if (
          confidenceDifference !== 0
        ) {
          return confidenceDifference;
        }

        /*
         * -----------------------------------------------------
         * FINAL — STABLE PRODUCT ID
         * -----------------------------------------------------
         */

        const aId =
          String(
            a.product?._id || ''
          );

        const bId =
          String(
            b.product?._id || ''
          );

        return aId.localeCompare(bId);
      });
    };

    /*
     * ---------------------------------------------------------
     * GROUP ELIGIBLE PRODUCTS BY CANONICAL CATEGORY
     * ---------------------------------------------------------
     */

    const productsByCategory =
      new Map(
        RECOMMENDATION_CATEGORIES.map(
          (category) => [
            category,
            [],
          ]
        )
      );

    eligibleProducts.forEach(
      (recommendation) => {
        const category =
          normalizeCategory(
            recommendation.product?.category
          );

        /*
         * Products whose category does not belong to the
         * canonical skinDecode category list are not included
         * in personalized category recommendations.
         *
         * They still remain available through allProducts.
         */
        if (!category) {
          return;
        }

        productsByCategory
          .get(category)
          .push(recommendation);
      }
    );

    /*
     * ---------------------------------------------------------
     * RANK EACH CATEGORY INDEPENDENTLY
     * ---------------------------------------------------------
     */

    const categoryRecommendations = [];

    RECOMMENDATION_CATEGORIES.forEach(
      (category) => {
        const categoryProducts =
          productsByCategory.get(category) || [];

        const rankedCategoryProducts =
          sortCategoryProducts(
            categoryProducts
          );

        rankedCategoryProducts
          .slice(
            0,
            RECOMMENDATIONS_PER_CATEGORY
          )
          .forEach(
            (recommendation, index) => {
              categoryRecommendations.push({
                ...recommendation,

                /*
                 * This is the important new field.
                 *
                 * It is ALWAYS relative to the product's
                 * own category.
                 */
                categoryRank:
                  index + 1,

                recommendationCategory:
                  category,

                /*
                 * Keep recommendationRank out of this layer.
                 *
                 * There is intentionally no global ranking.
                 */
                recommendationRank:
                  undefined,
              });
            }
          );
      }
    );

    console.log(
      `[ANON] Category ranking complete | ` +
      RECOMMENDATION_CATEGORIES
        .map((category) => {
          const count =
            categoryRecommendations.filter(
              (item) =>
                item.recommendationCategory ===
                category
            ).length;

          return `${category}=${count}`;
        })
        .join(' | ')
    );

    /*
     * ---------------------------------------------------------
     * 8. FINAL CATEGORY-AWARE RECOMMENDATIONS
     *
     * Each category contributes up to 5 products.
     *
     * There is NO global top-5.
     * ---------------------------------------------------------
     */

    const recommendedProducts =
      categoryRecommendations;

    /*
     * ---------------------------------------------------------
     * 9. FINAL RESPONSE
     *
     * IMPORTANT:
     *
     * Nothing is saved to SkinProfile.
     * Nothing is permanently saved to MongoDB
     * by this service.
     * ---------------------------------------------------------
     */

    const result = {
      profile,

      recommendedProducts,

      allProducts,

      consent: {
        consentId:
          consent.consentId,

        termsVersion:
          consent.termsVersion,

        privacyVersion:
          consent.privacyVersion,

        consentedAt:
          consent.consentedAt,
      },
    };

    console.log(
      `[ANON] Analysis COMPLETE: ${getElapsed(
        requestStart
      )}`
    );

    return result;
  };

export default {
  runAnonymousAnalysis,
};